name: Weekly

on:
  schedule:
    - cron: '0 10 * * 2'  # Every Tuesday at 10:00 UTC (6am ET)
  workflow_dispatch:      # Allow manual runs

jobs:
  run-nfl-edge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Goog
